import Head from 'next/head'
import styles from "@/styles/Userpath.module.css";
import {Center, Group, Text, Transition} from "@mantine/core";
import {useEffect, useState} from "react";
import HomePage from "@/components/HomePage";
import Animation from "@/components/Animation";

export default function Home(props) {
    const [mountContent, setMountContent] = useState(false);
    useEffect(() => {
        let visited = localStorage.getItem("visited");
        if(visited) setMountContent(true);
        if (!visited) {
            setTimeout(
                () => {
                    localStorage.setItem("visited", "true");
                    setMountContent(true);
                }, 5000
            );
        }
    })

    return (
        <>
            <Head>
                <title>AddMeOn</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <>
                    {
                        mountContent ?
                            <div className="animate__animated animate__fadeIn">
                                <HomePage/>
                            </div>
                            :
                            <Animation  {...props}/>
                    }
                </>
            </main>
        </>
    )
}
